'''
/**
 * @file gen_dri_defs.py
 *
 * @author awewsomegamer <awewsomegamer@gmail.com>
 *
 * @LICENSE
 * Arctan - Operating System
 * Copyright (C) 2023-2025 awewsomegamer
 *
 * This file is part of Arctan-OS/Kernel.
 *
 * Arctan is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; version 2
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * @DESCRIPTION
 * This file handles the management of the VFS's node graph, it is not intended
 * to be used by anything other than fs/vfs.c.
*/
'''

import sys
from pathlib import Path
from datetime import datetime, UTC

def get_group_indices_and_symbols(root_dir):
  source = list(Path(root_dir).rglob("*resource.h"))[0]
  symbols = {}
  recording = False
  idx = 0

  for line in list(open(str(source), "r")):
    if ("enum ARC_DRI_GROUP" in line):
      recording = True
      continue

    if ("};" in line):
      recording = False

    if (not recording):
      continue

    clean = line.strip().replace(' ','').split(',')[0]

    if ("=" in clean):
      t = clean.split("=")
      idx = int(t[1])
      clean = t[0]

    symbols[clean] = idx

    idx = idx + 1

  return symbols

def get_shared_groups(root_dir):
  source = list(Path(root_dir).rglob("*resource.h"))[0]
  shared = []

  for line in list(open(str(source), "r")):
      if (not "ARC_SHARE_DRIVER_INDICES" in line or "#define" in line):
        continue

      clean = line.replace(' ','').split("(")[1].split(")")[0]

      shared.append(clean.split(","))

  return shared

def enumerate_source_files(root_dir):
  definitions = {}

  sources = list(Path(root_dir).rglob("*.c"))
  for source in sources:
    print("Found source file:", str(source))

    for line in reversed(list(open(str(source), "r"))):
      if (not "ARC_REGISTER_DRIVER" in line or "#define" in line):
        continue

      clean = line.replace(' ', '').split('(')[1].split(')')[0].split(',')
      group = str(clean[0])
      name = str(clean[1])
      print("\tFound driver definition (GROUP: {0}, NAME: {1})".format(group, name))

      try:
        definitions[group].update({name:-1})
      except:
        definitions[group] = {name:-1}

  return definitions

def fill_in_indices(definitions, shared_groups, symbols):
  indices = {}
  for symbol in symbols:
    indices[symbol] = 0

  for definition in definitions:
    for name in definitions[definition]:
      idx = indices[definition]
      shared_increment = [definition]

      for cluster in shared_groups:
        if (definition in cluster):
          for shared_group in cluster:
            shared_increment.append(shared_group)
            idx = indices[shared_group]
          break

      shared_increment = list(set(shared_increment))

      for shared_group in shared_increment:
        if (not name in definitions[shared_group]):
          definitions[shared_group].update({name:-100})
        elif (name in definitions[shared_group] and definitions[shared_group][name] == -1):
          definitions[shared_group][name] = idx
          indices[shared_group] = idx + 1

  return definitions

header_preamble = '''/*
 * This file was generated by gen_dri_defs.py.
 * Date of Generation: {0}
*/

#ifndef AUTOGEN_ARC_DRIVERS_DRI_DEFS
#define AUTOGEN_ARC_DRIVERS_DRI_DEFS

#include \"drivers/resource.h\"
#include <stdint.h>
#include <stdint.h>

#define ARC_DRIDEF_PCI_TERMINATOR ((uint32_t)-1)
#define ARC_DRIDEF_ACPI_TERMINATOR ((uint64_t)-1)

extern const ARC_DriverDef _empty_driver;

'''.format(datetime.now(UTC).strftime("%d-%m-%Y"))

header_postamble = '''
int dridefs_int_func_empty();
size_t dridefs_size_t_func_empty();
void *dridefs_void_func_empty();

#endif // AUTOGEN_ARC_DRIVERS_DRI_DEFS
'''

def construct_dri_defs_header(definitions, out_file):
  out = open(out_file, "w")

  out.write(header_preamble)

  lines = []

  for definition in definitions:
    table_name = definition.replace("ARC_DRI_GROUP_", '')
    print("Generating definitions for table:", table_name.lower())

    lines.append("extern const ARC_DriverDef *arc_drivers_{0}[];\n".format(table_name.lower()))

    for name in definitions[definition]:
      idx = definitions[definition][name]
      if (idx < 0):
        continue

      lines.append("#define ARC_DRIDEF_{2}_{4} {3}\nextern ARC_DriverDef _{0}_{1};\n".format(name, definition, table_name, idx, name.upper()))

  for line in sorted(lines):
    print(line)
    out.write(line)

  out.write(header_postamble)

  return 0

source_preamble = '''/*
 * This file was generated by gen_dri_defs.py.
 * Date of Generation: {0}
*/

#include \"drivers/dri_defs.h\"

const ARC_DriverDef _empty_driver = {{
\t.init = dridefs_int_func_empty,
\t.uninit = dridefs_int_func_empty,
\t.read = dridefs_size_t_func_empty,
\t.write = dridefs_size_t_func_empty,
\t.seek = dridefs_int_func_empty,
\t.rename = dridefs_int_func_empty,
\t.stat = dridefs_int_func_empty,
\t.create = dridefs_int_func_empty,
\t.remove = dridefs_int_func_empty,
\t.locate = dridefs_void_func_empty,
}};

'''.format(datetime.now(UTC).strftime("%d-%m-%Y"))

source_postamble = '''
int dridefs_int_func_empty() {
\treturn -1;
}

size_t dridefs_size_t_func_empty() {
\treturn 0;
}

void *dridefs_void_func_empty() {
\treturn NULL;
}
'''

def construct_dri_defs_source(definitions, out_file):
  out = open(out_file, "w")

  out.write(source_preamble)

  for definition in definitions:
    table_name = definition.replace("ARC_DRI_GROUP_", '')
    print("Generating table:", table_name.lower())

    lines = []

    out.write("const ARC_DriverDef *arc_drivers_{0}[] = {{\n".format(table_name.lower()))

    for name in definitions[definition]:
      idx = definitions[definition][name]
      if (idx < 0):
        continue

      lines.append("\t[{2}] = &_{0}_{1},\n".format(name, definition, idx))

    for line in sorted(lines):
      out.write(line)

    out.write("};\n")

  out.write(source_postamble)

  return 0

def main():
  if (len(sys.argv) < 4):
    print("Usage: python gen_dri_defs.py path/to/source/root path/to/output/header/file path/to/output/source/file")
    return -1

  root_dir = sys.argv[1]
  header_out = sys.argv[2]
  source_out = sys.argv[3]

  symbols = get_group_indices_and_symbols(root_dir)
  shared = get_shared_groups(root_dir)
  definitions = enumerate_source_files(root_dir)
  definitions = fill_in_indices(definitions, shared, symbols)

  r = construct_dri_defs_header(definitions, header_out)
  r = r + construct_dri_defs_source(definitions, source_out)
  return r

if (__name__ == "__main__"):
    r = main()
    print("Cumulative Error:", r)
    sys.exit(r)
