'''
/**
 * @file gen_dri_defs.py
 *
 * @author awewsomegamer <awewsomegamer@gmail.com>
 *
 * @LICENSE
 * Arctan - Operating System
 * Copyright (C) 2023-2025 awewsomegamer
 *
 * This file is part of Arctan-OS/Kernel.
 *
 * Arctan is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; version 2
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * @DESCRIPTION
 * This file handles the management of the VFS's node graph, it is not intended
 * to be used by anything other than fs/vfs.c.
*/
'''

import sys
from pathlib import Path
from datetime import datetime, UTC

group_enum_prefix = "ARC_DRIGRP_"
driver_table_prefix = "arc_dris_"
definition_prefix = "ARC_DRIDEF_"

ARC_REGISTER_DRIVER = "ARC_REGISTER_DRIVER"
ARC_SHARE_DRIVER_INDICES = "ARC_SHARE_DRIVER_INDICES"

def get_group_indices_and_symbols(root_dir):
  source = list(Path(root_dir).rglob("*resource.h"))[0]
  symbols = {}
  recording = False
  idx = 0

  for line in list(open(str(source), "r")):
    if ("enum ARC_DRI_GROUP" in line):
      print("Found driver group enum, grabbing symbols")
      recording = True
      continue

    if ("};" in line):
      recording = False

    if (not recording):
      continue

    clean = line.strip().replace(' ','').split(',')[0]

    if ("=" in clean):
      t = clean.split("=")
      idx = int(t[1])
      clean = t[0]

    print("\t"+clean,"at",idx)
    symbols[clean] = idx

    idx = idx + 1

  return symbols

def get_shared_groups(root_dir):
  source = list(Path(root_dir).rglob("*resource.h"))[0]
  shared = []

  print("Looking for shared resources")
  for line in list(open(str(source), "r")):
      if (not ARC_SHARE_DRIVER_INDICES in line or "#define" in line):
        continue

      clean = line.replace(' ','').split("(")[1].split(")")[0]

      print("\t"+str(clean.split(",")),"are shared")
      shared.append(clean.split(","))

  return shared

def enumerate_source_files(root_dir):
  definitions = {}

  sources = list(Path(root_dir).rglob("*.c"))
  for source in sources:
    print("Found source file:", str(source))

    for line in reversed(list(open(str(source), "r"))):
      if (not ARC_REGISTER_DRIVER in line or "#define" in line):
        continue

      clean = line.replace(' ', '').split('(')[1].split(')')[0].split(',')
      group = str(clean[0])
      name = str(clean[1])
      print("\tFound driver definition (GROUP: {0}, NAME: {1})".format(group, name))

      try:
        definitions[group].update({name:-1})
      except:
        definitions[group] = {name:-1}

  return definitions

def fill_in_indices(definitions, shared_groups, symbols):
  indices = {}
  for symbol in symbols:
    indices[symbol] = 0

  for definition in definitions:
    for name in definitions[definition]:
      try:
        idx = indices[definition]
      except:
        print("ERROR: Unknown group \"{0}\", used on drivers:".format(definition))
        for name in definitions[definition]:
          print("\t"+name)
        sys.exit(-1)
      shared_increment = [definition]

      for cluster in shared_groups:
        if (definition in cluster):
          for shared_group in cluster:
            shared_increment.append(shared_group)
            idx = indices[shared_group]
          break

      shared_increment = list(set(shared_increment))

      for shared_group in shared_increment:
        if (not name in definitions[shared_group]):
          definitions[shared_group].update({name:-100})
        elif (name in definitions[shared_group] and definitions[shared_group][name] == -1):
          definitions[shared_group][name] = idx
          indices[shared_group] = idx + 1

  return definitions

def construct_dri_defs_header(definitions, out_file):
  header_preamble = '''/*
* This file was generated by gen_dri_defs.py.
* Date of Generation: {0}
*/

#ifndef AUTOGEN_ARC_DRIVERS_DRI_DEFS
#define AUTOGEN_ARC_DRIVERS_DRI_DEFS

#include \"drivers/resource.h\"
#include <stdint.h>
#include <stdint.h>
  
#define ARC_DRIDEF_DRIVER_GROUPS {2}
#define ARC_DRIDEF_CODES_TERMINATOR ((uint64_t)-1)

extern const ARC_DriverDef **{1}table[];
extern const ARC_DriverDef _empty_driver;

'''.format(datetime.now(UTC).strftime("%d-%m-%Y"), driver_table_prefix, len(definitions))

  header_postamble = '''
int dridefs_int_func_empty();
size_t dridefs_size_t_func_empty();
void *dridefs_void_func_empty();
size_t dridefs_get_entry_count(int group);

#endif // AUTOGEN_ARC_DRIVERS_DRI_DEFS
'''

  out = open(out_file, "w")

  out.write(header_preamble)

  lines = []

  for definition in definitions:
    table_name = definition.replace(group_enum_prefix, '')
    print("Generating definitions for table:", table_name.lower())

    lines.append("extern const ARC_DriverDef *{1}{0}[];\n".format(table_name.lower(), driver_table_prefix))

    for name in definitions[definition]:
      idx = definitions[definition][name]
      if (idx < 0):
        continue

      lines.append("#define {5}{2}_{4} {3}\nextern ARC_DriverDef _driver_{0}_{1};\n".format(name, definition, table_name, idx, name.upper(), definition_prefix))

  for line in sorted(lines):
    out.write(line)

  out.write(header_postamble)

  return 0


def construct_dri_defs_source(definitions, symbols, out_file):
  out = open(out_file, "w")

  source_preamble = '''/*
 * This file was generated by gen_dri_defs.py.
 * Date of Generation: {0}
*/

#include \"drivers/dri_defs.h\"

const ARC_DriverDef _empty_driver = {{
\t.init = dridefs_int_func_empty,
\t.uninit = dridefs_int_func_empty,
\t.read = dridefs_size_t_func_empty,
\t.write = dridefs_size_t_func_empty,
\t.seek = dridefs_int_func_empty,
\t.rename = dridefs_int_func_empty,
\t.stat = dridefs_int_func_empty,
\t.create = dridefs_int_func_empty,
\t.remove = dridefs_int_func_empty,
\t.locate = dridefs_void_func_empty,
}};

'''.format(datetime.now(UTC).strftime("%d-%m-%Y"))

  source_postamble = '''int dridefs_int_func_empty() {
\treturn -1;
}

size_t dridefs_size_t_func_empty() {
\treturn 0;
}

void *dridefs_void_func_empty() {
\treturn NULL;
}
'''
  
  out.write(source_preamble)

  for definition in definitions:
    table_name = definition.replace(group_enum_prefix, '')
    print("Generating table:", table_name.lower())

    lines = []

    largest_idx = definitions[definition][max(definitions[definition], key=definitions[definition].get)] + 1
    out.write("const ARC_DriverDef *{2}{0}[{1}] = {{\n".format(table_name.lower(), largest_idx, driver_table_prefix))

    for i in range(largest_idx):
      lines.append("\t[{0}] = NULL,\n".format(i))
    
    for name in definitions[definition]:
      idx = definitions[definition][name]

      if (idx < 0):
        continue
      
      lines[idx] = "\t[{2}] = &_driver_{0}_{1},\n".format(name, definition, idx)
      
    for line in sorted(lines):
      out.write(line)

    out.write("};\n\n")

  lines = []
  largest_idx = symbols[max(symbols, key=symbols.get)] + 1
  out.write("const ARC_DriverDef **{0}table[{1}] = {{\n".format(driver_table_prefix, largest_idx))  
  for symbol in symbols:
    table_name = symbol.replace(group_enum_prefix, '')
    lines.append("\t[{0}] = {1}{2},\n".format(symbols[symbol], driver_table_prefix, table_name.lower()))

  for line in sorted(lines):
    out.write(line)

  out.write("};\n\n")
  
  lines = []
  out.write("size_t dridefs_get_entry_count(int group) {{\n\tif (group >= {0}) {{\n\t\treturn 0;\n\t}}\n\n\tswitch(group) {{\n".format(len(symbols)))

  for symbol in symbols:
    largest_idx = definitions[symbol][max(definitions[symbol], key=definitions[symbol].get)] + 1
    table_name = symbol.replace(group_enum_prefix, '')
    lines.append("\t\tcase {0}:\n\t\t\treturn {1};\n\t\t\tbreak;\n".format(symbols[symbol], largest_idx))
    
  for line in lines:
    out.write(line)
    
  out.write("\t}\n}\n\n")
  
  out.write(source_postamble)

  return 0

def main():
  if (len(sys.argv) < 4):
    print("Usage: python gen_dri_defs.py path/to/source/root path/to/output/header/file path/to/output/source/file")
    return -1

  root_dir = sys.argv[1]
  header_out = sys.argv[2]
  source_out = sys.argv[3]

  symbols = get_group_indices_and_symbols(root_dir)
  shared = get_shared_groups(root_dir)
  definitions = enumerate_source_files(root_dir)
  definitions = fill_in_indices(definitions, shared, symbols)

  r = construct_dri_defs_header(definitions, header_out)
  r = r + construct_dri_defs_source(definitions, symbols, source_out)
  return r

if (__name__ == "__main__"):
    r = main()
    print("Cumulative Error:", r)
    sys.exit(r)
