/*
 * This file was autogenerated by gen_dri_defs.py.
 * Date of Generation: 08-12-2024
*/
#ifndef AUTOGEN_ARC_DRIVERS_DRI_DEFS
#define AUTOGEN_ARC_DRIVERS_DRI_DEFS
#include <lib/resource.h>

#define ARC_DRIDEF_INITRAMFS_SUPER 0
extern struct ARC_DriverDef __driver_initramfs_super;
#define ARC_DRIDEF_INITRAMFS_FILE 1
extern struct ARC_DriverDef __driver_initramfs_file;
#define ARC_DRIDEF_BUFFER_SUPER 2
extern struct ARC_DriverDef __driver_buffer_super;
#define ARC_DRIDEF_BUFFER_FILE 3
extern struct ARC_DriverDef __driver_buffer_file;
#define ARC_DRIDEF_EXT2_SUPER 4
extern struct ARC_DriverDef __driver_ext2_super;
#define ARC_DRIDEF_EXT2_FILE 5
extern struct ARC_DriverDef __driver_ext2_file;
#define ARC_DRIDEF_NVME_NAMESPACE 6
extern struct ARC_DriverDef __driver_nvme_namespace_;
#define ARC_DRIDEF_NVME 7
extern struct ARC_DriverDef __driver_nvme_;
#define ARC_DRIDEF_COUNT 8
#define ARC_DRIDEF_PCI_TERMINATOR 0xFFFFFFFF
extern struct ARC_DriverDef *__DRIVER_LOOKUP_TABLE[];
#endif // AUTOGEN_ARC_DRIVERS_DRI_DEFS
